[package]
name = "frugger_core"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8.1"
heapless = "0.8.0"

[dev-dependencies]
embedded-graphics-simulator = "0.6.0"
sdl2 = { version = "0.35.1", features = ["bundled"] }